project:
  type: book

book:
  title: "iSEETheBook"
  author: "Kevin Rue-Albrecht"
  search: true
  repo-url: https://github.com/iSEE/iSEETheBook/
  repo-actions: [edit]
  date: "8/23/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - ui.qmd
    - first.qmd
    - contributing.qmd
    - authors.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - theme.scss
    link-external-icon: true
    link-external-newwindow: true
#  pdf:
#    documentclass: scrreprt



