project:
  type: book

book:
  title: "iSEETheBook"
  author: "Kevin Rue-Albrecht"
  date: "8/23/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - ui.qmd
    - first.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - theme.scss
#  pdf:
#    documentclass: scrreprt



